---
- name: Update apt
  import_tasks: update.yml

- name: Install core packages
  import_tasks: core.yml

- name: Install mise
  import_tasks: mise.yml

- name: Install docker
  import_tasks: docker.yml

- name: Install GitHub CLI
  import_tasks: gh.yml

- name: Install AI agents
  import_tasks: agents.yml

- name: Install nix
  import_tasks: nix.yml

- name: Harden SSH configuration
  import_tasks: ssh-hardening.yml

- name: Harden VM
  import_tasks: hardening.yml
